# Site settings
title: å¿½å—å¿½åŒ—Wq
SEOTitle: æ— ç©·çš„ä¸­æ–‡Blog | Li Wuqiong
header-img: img/home-bg.jpg
email: liwuqiong@hotmail.com
description: "è¿™é‡Œæ˜¯ ææ— ç©·@liwuqiong çš„ä¸ªäººä¸­æ–‡åšå®¢ï¼Œä¸ä½ ä¸€èµ·å‘ç°æ›´å¤§çš„ä¸–ç•Œ | åšä¸€ä¸ªåŒè¯­å†™ä½œè€…"
# keyword: "æ— ç©·, ææ— ç©·ï¼Œliwuqiong, wuqiong, wuqiongli, å¿½å—å¿½åŒ—, @liwuqiong, æ— ç©·çš„æ—è¯­, æ— ç©·çš„åšå®¢, Wuqiong Blog, åšå®¢, ä¸ªäººç½‘ç«™, äº’è”ç½‘, Web, ç”µå•†, äººå·¥æ™ºèƒ½, æ•°æ®åˆ†æ, Jekyll"
url: "https://liwuqiong.com" # your host, for absolute URL
baseurl: "/blog_zh" # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
weibo_username: liwuqiong
zhihu_username: liwuqiong
# github_username: liwuqiong
twitter_username: rucliwuqiong
#facebook_username:  huxpro
#linkedin_username:  firstname-lastname-idxxxx

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: /:title
paginate: 10
exclude:
  [
    "less",
    "node_modules",
    "Gruntfile.js",
    "package.json",
    "README.md",
    "README.zh.md",
  ]
anchorjs: true # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN

# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Disqus settings
# disqus_username: liwuqiong

# Netease settings
netease_comment: false

# Analytics settings
# Baidu Analytics
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: "G-N9076HRDQH" # Format: UA-xxxxxx-xx
ga_domain: liwuqiong.com/blog_zh

# Sidebar settings
sidebar: true # whether or not using Sidebar.
sidebar-about-description: "ğŸš€Entrepreneur <br>ğŸ“ˆAnalyst <br>ğŸ’»Developer <br>âœï¸Writer <br> ğŸ‘¨â€ğŸ”¬Researcher <br>æ­£åœ¨æˆä¸ºä¸€ååŒè¯­å†™ä½œè€… <br> æ–‡å­—ç©¿è¶Šæ—¶é—´"
sidebar-avatar: "https://liwuqiong.com/blog_zh/img/me.jpg" # use absolute URL, seeing it's used in both `/` and `/about/`

# Featured Tags
featured-tags: true # whether or not using Feature-Tags
featured-condition-size: 1 # A tag will be featured if the size of it is more than this condition value

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false

# Friends
# friends:
#   [
#     { title: "ä¹±åºï¼ˆMidareï¼‰", href: "http://mida.re/" },
#     { title: "Ebn Zhang", href: "https://ebnbin.dev/" },
#     { title: "Kun Qian", href: "http://kunq.me" },
#     { title: "Sherry Woo", href: "https://sherrywoo.me/" },
#     { title: "SmdCn", href: "http://blog.smdcn.net" },
#     { title: "JiyinYiyong", href: "http://tiye.me/" },
#     { title: "DHong Say", href: "http://dhong.co" },
#     { title: "å°¹å³°ä»¥ä¸º", href: "http://ingf.github.io/" },
#   ]
